from __future__ import annotations

"""Generate a literature review Markdown report from the cleaned dataset.

The module loads the cleaned dataset (default: data/processed/cleaned_papers.csv),
computes summary statistics and extracts frequent themes, datasets, benchmarks,
and metrics, and writes a structured Markdown report to reports/report.md.

Design:
- Each section is generated by a dedicated function to keep the code testable.
- Uses the keywords and analyze utilities for token extraction and statistics.
- Uses a small curated list of dataset/benchmark/metric names to detect mentions in
  the corpus; this is intentionally conservative and extendable.
"""

from collections import Counter
import logging
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import pandas as pd

from .keywords import top_keywords_from_texts
from .analyze import compute_most_common_authors, publication_counts_by_year, category_frequencies, average_abstract_length, most_common_topics

logger = logging.getLogger(__name__)

DEFAULT_INPUT = Path("data") / "processed" / "cleaned_papers.csv"
OUTPUT_PATH = Path("reports") / "report.md"

# Curated lists for entity detection. Extend as needed.
COMMON_DATASETS = [
    "imagenet",
    "cifar",
    "mnist",
    "squad",
    "glue",
    "coco",
    "pubmed",
    "wikitext",
    "squad2",
    "squad_v2",
    "squad_v1",
    "squad2.0",
    "squad1.1",
    "squad1",
    "sst",
    "msmarco",
    "ms marco",
    "ms-marco",
    "coqa",
    "sbu",
    "yelp",
    "wmt",
    "yahoo",
    "agnews",
]

COMMON_BENCHMARKS = [
    "glue",
    "superglue",
    "imagenet",
    "squad",
    "mnli",
    "squad2",
    "coco",
]

COMMON_METRICS = [
    "accuracy",
    "f1",
    "precision",
    "recall",
    "bleu",
    "rouge",
    "perplexity",
    "auc",
    "auroc",
    "map",
    "mAP",
    "em",
    "wer",
    "mae",
    "mse",
]


# --------------------
# Helpers
# --------------------


def _load_cleaned(path: Path = DEFAULT_INPUT) -> pd.DataFrame:
    logger.info("Loading cleaned dataset from %s", path)
    df = pd.read_csv(path)
    logger.info("Loaded %d rows", len(df))
    return df


def _count_entity_mentions(texts: Iterable[str], keywords: Iterable[str]) -> Counter:
    """Count mentions of keywords in texts (case-insensitive).

    Returns a Counter mapping lowercase keyword -> count.
    """
    counter: Counter = Counter()
    kw_list = [k.lower() for k in keywords]
    for t in texts:
        if not isinstance(t, str):
            continue
        s = t.lower()
        for kw in kw_list:
            if kw in s:
                counter[kw] += s.count(kw)
    return counter


def _format_top_list(items: Iterable[Tuple[str, int]], limit: int = 10) -> str:
    lines = []
    for i, (item, count) in enumerate(items):
        if i >= limit:
            break
        lines.append(f"- **{item}** — {count} mentions")
    return "\n".join(lines)


# --------------------
# Section generators
# --------------------


def research_objective_section() -> str:
    return (
        "# Literature Review\n\n"
        "This report summarizes themes, datasets, benchmarks, and evaluation metrics "
        "found in the corpus of cleaned research paper abstracts. The goal is to "
        "provide a concise synthesis of common research topics and empirical "
        "practices to inform further analysis and meta-research.\n"
    )


def dataset_summary_section(df: pd.DataFrame) -> str:
    total = len(df)
    years_df = publication_counts_by_year(df)
    categories_df = category_frequencies(df).head(10)
    avg_len_df = average_abstract_length(df)

    summary_lines = [
        "## Dataset summary\n",
        f"- Number of papers: **{total}*\n",
    ]

    if not years_df.empty:
        years_preview = years_df.tail(10).to_dict(orient="records")
        summary_lines.append("- Recent publication counts by year (last 10 years):\n")
        for r in years_preview:
            summary_lines.append(f"  - {int(r['year'])}: {int(r['count'])}\n")

    if not categories_df.empty:
        summary_lines.append("- Top categories:\n")
        for _, row in categories_df.iterrows():
            summary_lines.append(f"  - {row['category']}: {int(row['count'])}\n")

    if not avg_len_df.empty:
        row = avg_len_df.iloc[0]
        summary_lines.append(
            f"- Average abstract length: **{row['avg_words']:.1f} words**, median **{row['median_words']:.1f} words**\n"
        )

    return "".join(summary_lines)


def frequent_themes_section(df: pd.DataFrame, top_n: int = 20) -> str:
    # Use both abstract and title cleaned text for theme extraction
    texts = []
    if "abstract_clean" in df.columns:
        texts.extend(df["abstract_clean"].astype(str).tolist())
    if "title_clean" in df.columns:
        texts.extend(df["title_clean"].astype(str).tolist())

    kw_pairs = top_keywords_from_texts(texts, top_n=top_n)
    md = ["## Frequently occurring research themes\n"]
    md.append(_format_top_list(kw_pairs, limit=top_n))
    md.append("\n")

    # Also include bi/tri-grams as topics
    topics_df = most_common_topics(df, text_column="abstract_clean", ngram_range=(2, 3), top_n=20)
    if not topics_df.empty:
        md.append("### Common multi-word topics\n")
        for _, row in topics_df.head(10).iterrows():
            md.append(f"- **{row['topic']}** — {int(row['count'])} occurrences\n")
    return "".join(md)


def common_datasets_section(df: pd.DataFrame, limit: int = 20) -> str:
    texts = df["abstract_clean"].astype(str).tolist() if "abstract_clean" in df.columns else []
    counts = _count_entity_mentions(texts, COMMON_DATASETS)
    if not counts:
        return "## Common datasets\n\n_No dataset mentions detected._\n"
    items = counts.most_common(limit)
    md = ["## Common datasets\n\n"]
    for k, v in items:
        md.append(f"- **{k}** — {v} mentions\n")
    return "".join(md)


def common_benchmarks_section(df: pd.DataFrame, limit: int = 20) -> str:
    texts = df["abstract_clean"].astype(str).tolist() if "abstract_clean" in df.columns else []
    counts = _count_entity_mentions(texts, COMMON_BENCHMARKS)
    if not counts:
        return "## Frequently referenced benchmarks\n\n_No benchmark mentions detected._\n"
    items = counts.most_common(limit)
    md = ["## Frequently referenced benchmarks\n\n"]
    for k, v in items:
        md.append(f"- **{k}** — {v} mentions\n")
    return "".join(md)


def common_metrics_section(df: pd.DataFrame, limit: int = 20) -> str:
    texts = df["abstract_clean"].astype(str).tolist() if "abstract_clean" in df.columns else []
    counts = _count_entity_mentions(texts, COMMON_METRICS)
    if not counts:
        return "## Common evaluation metrics\n\n_No metric mentions detected._\n"
    items = counts.most_common(limit)
    md = ["## Common evaluation metrics\n\n"]
    for k, v in items:
        md.append(f"- **{k}** — {v} mentions\n")
    return "".join(md)


def key_observations_section(df: pd.DataFrame) -> str:
    authors_df = compute_most_common_authors(df, top_n=10)
    obs = ["## Key observations\n\n"]
    obs.append("- Many papers cluster around the following authors/groups (top 10):\n")
    for _, row in authors_df.iterrows():
        obs.append(f"  - {row['author']}: {int(row['count'])} papers\n")
    obs.append("\n- Topic extraction and keyword frequencies are provided above; these reflect repeated empirical focuses across the corpus.\n")
    return "".join(obs)


def limitations_section() -> str:
    return (
        "## Limitations\n\n"
        "- The report is generated from cleaned abstracts and titles only; full-text analysis may reveal additional topics and evaluation setups.\n"
        "- Entity detection for datasets/benchmarks/metrics uses a curated list and substring matching; false positives/negatives are possible.\n"
        "- Tokenization and keyword extraction are simplistic (whitespace-based); more advanced NLP (TF-IDF, phrase detection, named entity recognition) could improve topic identification.\n"
    )


def future_work_section() -> str:
    return (
        "## Future work\n\n"
        "- Expand entity detection using named-entity recognition and curated gazetteers for datasets and benchmarks.\n"
        "- Integrate TF-IDF and topic modeling (LDA, NMF) to surface latent research themes.\n"
        "- Correlate topics with empirical practices (datasets, metrics) and track trends over time.\n"
        "- Add visualization of trends and networks (co-authorship, topic co-occurrence) and include them in reports/ and graphs/.\n"
    )


def generate_report(input_path: Optional[Path] = None, output_path: Optional[Path] = None) -> Path:
    input_path = input_path or DEFAULT_INPUT
    output_path = output_path or OUTPUT_PATH
    df = _load_cleaned(input_path)

    logger.info("Generating literature review report")
    parts: List[str] = []
    parts.append(research_objective_section())
    parts.append("\n")
    parts.append(dataset_summary_section(df))
    parts.append("\n")
    parts.append(frequent_themes_section(df))
    parts.append("\n")
    parts.append(common_datasets_section(df))
    parts.append("\n")
    parts.append(common_benchmarks_section(df))
    parts.append("\n")
    parts.append(common_metrics_section(df))
    parts.append("\n")
    parts.append(key_observations_section(df))
    parts.append("\n")
    parts.append(limitations_section())
    parts.append("\n")
    parts.append(future_work_section())

    output_text = "\n".join(parts)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(output_text)

    logger.info("Wrote literature review to %s", output_path)
    return output_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser("generate-review")
    parser.add_argument("--in", dest="input", type=str, default=None, help="Cleaned CSV path")
    parser.add_argument("--out", dest="out", type=str, default=None, help="Output Markdown path")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s: %(message)s")
    path = generate_report(input_path=Path(args.input) if args.input else None, output_path=Path(args.out) if args.out else None)
    print(f"Wrote report to: {path}")
